name: nightly-build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Hourly “At :00”

jobs:
  build:
    if: ${{ github.repository_owner == 'jrobrien91' }}
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_name: suli-seminar
      environment_file: environment.yml
      path_to_notebooks: ./
  link-check:
    if: ${{ github.repository_owner == 'jrobrien91' }}
    uses: ProjectPythia/cookbook-actions/.github/workflows/link-checker.yaml@main
    with:
      environment_name: suli-seminar
      environment_file: environment.yml
      path_to_notebooks: ./
  deploy:
    needs: build
    uses: ProjectPythia/cookbook-actions/.github/workflows/deploy-book.yaml@main
