name: trigger-book-build
on:
  pull_request:

jobs:
  build:
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_name: suli-seminar
      environment_file: environment.yml
      path_to_notebooks: ./
      use_cached_environment: 'true'  # This is default, not strickly needed. Set to 'false' to always build a new environment
      artifact_name: book-zip-${{ github.event.number }}
      # Other input options are possible, see ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml
